apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cart-api
  template:
    metadata:
      labels:
        run: cart-api
    spec:
      containers:
      - name: cart-api
        image: mthom1035/gca_deployment:cart_api
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"