apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: catalog-api
  template:
    metadata:
      labels:
        run: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: mthom1035/gca_deployment:catalog_api
        ports:
        - containerPort: 8080
        env:
          - name: CART_API_USERNAME
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: cart_api_username
          - name: CART_API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: cart_api_password
          - name: CHECKOUT_API_USERNAME
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: checkout_api_username
          - name: CHECKOUT_API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: checkout_api_password
          - name: FRONTEND_USERNAME
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: frontend_username
          - name: FRONTEND_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-credentials
                key: frontend_password
        resources:
          requests:
            cpu: "150m"
            memory: "100Mi"
          limits:
            cpu: "250m"
            memory: "250Mi"

            