apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
type: Opaque
data:
  frontend_username: frontendUser
  frontend_password: frontendPassword
  checkout_api_username: checkoutUser
  checkout_api_password: checkoutPassword
  cart_api_username: cartUser
  cart_api_password: cartPassword
  shipping_api_username: shippingUser
  shipping_api_password: shippingPassword