apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
data:
  frontend_username: ZnJvbnRlbmRVc2Vy
  frontend_password: ZnJvbnRlbmRQYXNzd29yZA==
  checkout_api_username: Y2hlY2tvdXRVc2Vy
  checkout_api_password: Y2hlY2tvdXRQYXNzd29yZA==
  cart_api_username: Y2FydFVzZXI=
  cart_api_password: Y2FydFBhc3N3b3Jk
  shipping_api_username: c2hpcHBpbmdVc2Vy
  shipping_api_password: c2hpcHBpbmdQYXNzd29yZA==
