kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-shipping-volume
  labels:
    type: local
    app: database-shipping
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/dataShipping"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: databaseshipping-pv-claim
  labels:
    app: database-shipping
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi